// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: anti_bruteforce_service.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqAllowAuthorization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqAllowAuthorization) Reset() {
	*x = ReqAllowAuthorization{}
	mi := &file_anti_bruteforce_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqAllowAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAllowAuthorization) ProtoMessage() {}

func (x *ReqAllowAuthorization) ProtoReflect() protoreflect.Message {
	mi := &file_anti_bruteforce_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAllowAuthorization.ProtoReflect.Descriptor instead.
func (*ReqAllowAuthorization) Descriptor() ([]byte, []int) {
	return file_anti_bruteforce_service_proto_rawDescGZIP(), []int{0}
}

func (x *ReqAllowAuthorization) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *ReqAllowAuthorization) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ReqAllowAuthorization) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type ResAllowAuthorization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allow         bool                   `protobuf:"varint,1,opt,name=allow,proto3" json:"allow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResAllowAuthorization) Reset() {
	*x = ResAllowAuthorization{}
	mi := &file_anti_bruteforce_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResAllowAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResAllowAuthorization) ProtoMessage() {}

func (x *ResAllowAuthorization) ProtoReflect() protoreflect.Message {
	mi := &file_anti_bruteforce_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResAllowAuthorization.ProtoReflect.Descriptor instead.
func (*ResAllowAuthorization) Descriptor() ([]byte, []int) {
	return file_anti_bruteforce_service_proto_rawDescGZIP(), []int{1}
}

func (x *ResAllowAuthorization) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

type ReqNetwork struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqNetwork) Reset() {
	*x = ReqNetwork{}
	mi := &file_anti_bruteforce_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqNetwork) ProtoMessage() {}

func (x *ReqNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_anti_bruteforce_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqNetwork.ProtoReflect.Descriptor instead.
func (*ReqNetwork) Descriptor() ([]byte, []int) {
	return file_anti_bruteforce_service_proto_rawDescGZIP(), []int{2}
}

func (x *ReqNetwork) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type ResListNetworks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Networks      []string               `protobuf:"bytes,1,rep,name=networks,proto3" json:"networks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResListNetworks) Reset() {
	*x = ResListNetworks{}
	mi := &file_anti_bruteforce_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResListNetworks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResListNetworks) ProtoMessage() {}

func (x *ResListNetworks) ProtoReflect() protoreflect.Message {
	mi := &file_anti_bruteforce_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResListNetworks.ProtoReflect.Descriptor instead.
func (*ResListNetworks) Descriptor() ([]byte, []int) {
	return file_anti_bruteforce_service_proto_rawDescGZIP(), []int{3}
}

func (x *ResListNetworks) GetNetworks() []string {
	if x != nil {
		return x.Networks
	}
	return nil
}

type ReqCleanBucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqCleanBucket) Reset() {
	*x = ReqCleanBucket{}
	mi := &file_anti_bruteforce_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqCleanBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqCleanBucket) ProtoMessage() {}

func (x *ReqCleanBucket) ProtoReflect() protoreflect.Message {
	mi := &file_anti_bruteforce_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqCleanBucket.ProtoReflect.Descriptor instead.
func (*ReqCleanBucket) Descriptor() ([]byte, []int) {
	return file_anti_bruteforce_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReqCleanBucket) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *ReqCleanBucket) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

var File_anti_bruteforce_service_proto protoreflect.FileDescriptor

const file_anti_bruteforce_service_proto_rawDesc = "" +
	"\n" +
	"\x1danti_bruteforce_service.proto\x12\x0eantibruteforce\x1a\x1bgoogle/protobuf/empty.proto\"Y\n" +
	"\x15ReqAllowAuthorization\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\"-\n" +
	"\x15ResAllowAuthorization\x12\x14\n" +
	"\x05allow\x18\x01 \x01(\bR\x05allow\"&\n" +
	"\n" +
	"ReqNetwork\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\"-\n" +
	"\x0fResListNetworks\x12\x1a\n" +
	"\bnetworks\x18\x01 \x03(\tR\bnetworks\"6\n" +
	"\x0eReqCleanBucket\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip2\x9c\x05\n" +
	"\x15AntiBruteForceService\x12d\n" +
	"\x12AllowAuthorization\x12%.antibruteforce.ReqAllowAuthorization\x1a%.antibruteforce.ResAllowAuthorization\"\x00\x12M\n" +
	"\x15AddNetworkToWhitelist\x12\x1a.antibruteforce.ReqNetwork\x1a\x16.google.protobuf.Empty\"\x00\x12R\n" +
	"\x1aDeleteNetworkFromWhitelist\x12\x1a.antibruteforce.ReqNetwork\x1a\x16.google.protobuf.Empty\"\x00\x12F\n" +
	"\tWhitelist\x12\x16.google.protobuf.Empty\x1a\x1f.antibruteforce.ResListNetworks\"\x00\x12M\n" +
	"\x15AddNetworkToBlacklist\x12\x1a.antibruteforce.ReqNetwork\x1a\x16.google.protobuf.Empty\"\x00\x12R\n" +
	"\x1aDeleteNetworkFromBlacklist\x12\x1a.antibruteforce.ReqNetwork\x1a\x16.google.protobuf.Empty\"\x00\x12F\n" +
	"\tBlacklist\x12\x16.google.protobuf.Empty\x1a\x1f.antibruteforce.ResListNetworks\"\x00\x12G\n" +
	"\vCleanBucket\x12\x1e.antibruteforce.ReqCleanBucket\x1a\x16.google.protobuf.Empty\"\x00B\aZ\x05.;apib\x06proto3"

var (
	file_anti_bruteforce_service_proto_rawDescOnce sync.Once
	file_anti_bruteforce_service_proto_rawDescData []byte
)

func file_anti_bruteforce_service_proto_rawDescGZIP() []byte {
	file_anti_bruteforce_service_proto_rawDescOnce.Do(func() {
		file_anti_bruteforce_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anti_bruteforce_service_proto_rawDesc), len(file_anti_bruteforce_service_proto_rawDesc)))
	})
	return file_anti_bruteforce_service_proto_rawDescData
}

var file_anti_bruteforce_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_anti_bruteforce_service_proto_goTypes = []any{
	(*ReqAllowAuthorization)(nil), // 0: antibruteforce.ReqAllowAuthorization
	(*ResAllowAuthorization)(nil), // 1: antibruteforce.ResAllowAuthorization
	(*ReqNetwork)(nil),            // 2: antibruteforce.ReqNetwork
	(*ResListNetworks)(nil),       // 3: antibruteforce.ResListNetworks
	(*ReqCleanBucket)(nil),        // 4: antibruteforce.ReqCleanBucket
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_anti_bruteforce_service_proto_depIdxs = []int32{
	0, // 0: antibruteforce.AntiBruteForceService.AllowAuthorization:input_type -> antibruteforce.ReqAllowAuthorization
	2, // 1: antibruteforce.AntiBruteForceService.AddNetworkToWhitelist:input_type -> antibruteforce.ReqNetwork
	2, // 2: antibruteforce.AntiBruteForceService.DeleteNetworkFromWhitelist:input_type -> antibruteforce.ReqNetwork
	5, // 3: antibruteforce.AntiBruteForceService.Whitelist:input_type -> google.protobuf.Empty
	2, // 4: antibruteforce.AntiBruteForceService.AddNetworkToBlacklist:input_type -> antibruteforce.ReqNetwork
	2, // 5: antibruteforce.AntiBruteForceService.DeleteNetworkFromBlacklist:input_type -> antibruteforce.ReqNetwork
	5, // 6: antibruteforce.AntiBruteForceService.Blacklist:input_type -> google.protobuf.Empty
	4, // 7: antibruteforce.AntiBruteForceService.CleanBucket:input_type -> antibruteforce.ReqCleanBucket
	1, // 8: antibruteforce.AntiBruteForceService.AllowAuthorization:output_type -> antibruteforce.ResAllowAuthorization
	5, // 9: antibruteforce.AntiBruteForceService.AddNetworkToWhitelist:output_type -> google.protobuf.Empty
	5, // 10: antibruteforce.AntiBruteForceService.DeleteNetworkFromWhitelist:output_type -> google.protobuf.Empty
	3, // 11: antibruteforce.AntiBruteForceService.Whitelist:output_type -> antibruteforce.ResListNetworks
	5, // 12: antibruteforce.AntiBruteForceService.AddNetworkToBlacklist:output_type -> google.protobuf.Empty
	5, // 13: antibruteforce.AntiBruteForceService.DeleteNetworkFromBlacklist:output_type -> google.protobuf.Empty
	3, // 14: antibruteforce.AntiBruteForceService.Blacklist:output_type -> antibruteforce.ResListNetworks
	5, // 15: antibruteforce.AntiBruteForceService.CleanBucket:output_type -> google.protobuf.Empty
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_anti_bruteforce_service_proto_init() }
func file_anti_bruteforce_service_proto_init() {
	if File_anti_bruteforce_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anti_bruteforce_service_proto_rawDesc), len(file_anti_bruteforce_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_anti_bruteforce_service_proto_goTypes,
		DependencyIndexes: file_anti_bruteforce_service_proto_depIdxs,
		MessageInfos:      file_anti_bruteforce_service_proto_msgTypes,
	}.Build()
	File_anti_bruteforce_service_proto = out.File
	file_anti_bruteforce_service_proto_goTypes = nil
	file_anti_bruteforce_service_proto_depIdxs = nil
}
